name: Minify commands.js

on:
  push:
    paths:
      - 'assets/commands.js'

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Terser
        run: npm install terser -g
      - name: Minify commands.js
        run: terser assets/commands.js -o assets/commands.min.js --compress --mangle
      - name: Commit and push minified file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/commands.min.js
          git commit -m "chore: auto-minify commands.js" || echo "No changes to commit"
          git push 